### ISSUE TITLE
Converting VideoFrame to canvas images or WebGL textures is very slow

### ISSUE THREAD

**Issue by xfq** [w3c/webcodecs#421]
When using `VideoFrame` as the textures of Three.js, we found that it's very slow. When decoding a 3840x3840 video only, the frame rate is about 80fps; adding `frame.clone()` it is still about 80fps. But after adding `drawImage` or `texSubImage2D`, the frame rate dropped to about 10fps:

![145173495-6d56f34f-8ff8-4894-886a-92cd9d90dfca](https://user-images.githubusercontent.com/2863444/145521613-65f29eb4-fd0f-4123-a511-f962606e0339.png)

Can anyone point me in the right direction?

**Comment by shaoboyan** [comment]
(If it happens in  chrome)
I suspect that the `VideoFrame` you got from decoder is backed by CPU resources(Which means, the GPU decoder not works, because of profiles). One simple way to check this with chrome is that you could use HTMLVideoElement to play your video and use chrome://media-internals to see the decoder it uses.

**Comment by kareljuricka** [comment]
I think it can be related to my issue - https://bugs.chromium.org/p/chromium/issues/detail?id=1272288 , which is fixed already and will be released in newer Chrome versions. Try Chrome Canary to compare performance. They already applied fix there.

**Comment by xfq** [comment]
> (If it happens in chrome) I suspect that the `VideoFrame` you got from decoder is backed by CPU resources(Which means, the GPU decoder not works, because of profiles). One simple way to check this with chrome is that you could use HTMLVideoElement to play your video and use chrome://media-internals to see the decoder it uses.

`kVideoDecoderName` is `D3D11VideoDecoder`.

**Comment by xfq** [comment]
> I think it can be related to my issue - https://bugs.chromium.org/p/chromium/issues/detail?id=1272288 , which is fixed already and will be released in newer Chrome versions. Try Chrome Canary to compare performance. They already applied fix there.

Thanks. `drawImage` is faster in Chrome Canary, but `texSubImage2D` is the same as before (the frame rate is still very low).

**Comment by shaoboyan** [comment]
@xfq  Would you mind to provide the use case and I can take a look at it.

**Comment by xfq** [comment]
@shaoboyan The use case is volumetric video. See https://github.com/w3c/strategy/issues/286

Since it is possible to convert from Canvas 2D to `CanvasTexture` in three.js, and this is really an impl issue, not a spec issue, I'll close it.

If you think we need a Chromium bug to track the `texSubImage2D` performance issue, I can file one. Thank you for your help!

**Comment by shaoboyan** [comment]
@xfq Yes, pls help to file a bug in chromium to track `texSubImage2D`, thanks!

**Comment by chcunningham** [comment]
@xfq - just checking in on the chrome bug. Was it fixed as suspected by https://github.com/w3c/webcodecs/issues/421#issuecomment-990716303?

**Comment by xfq** [comment]
@chcunningham `drawImage` was fixed, but `texSubImage2D` is still slow. I have filed https://bugs.chromium.org/p/chromium/issues/detail?id=1279351

**Comment by ziyunfei** [comment]
This Chrome bug still repros for me, we are using Webcodecs + Puppeteer for video rendering, when drawing a large `VideoFrame` to canvas, it's very slow,  and the odd thing is, it's slow but doesn't cost much CPU usage.

Here is the perf data measured on our servers (the test case is scaling this 2160x3840 video https://a1.alibabausercontent.com/prod/feupload/user/vts0/2e68d1a0-684b-11ec-b9df-fb99023e8493.mov_.mp4 to 800x1200): 

```
pouch(https://github.com/alibaba/pouch) 4-core
ffmpeg: 10s
chrome 95: 35s
chrome 96-99: 85s

pod(k8s) 32-core
ffmpeg: 5s
chrome 95: 60s
chrome 96-99: 145s
```

![image](https://user-images.githubusercontent.com/1276859/147644458-dc9a0746-98d7-4524-93a9-75dda65ca3c2.png)
